import type { PrismaClient } from "@prisma/client";

function createEnumSql(name: string, values: string[]) {
  const listed = values.map((value) => `'${value}'`).join(", ");
  return `DO $$ BEGIN CREATE TYPE "${name}" AS ENUM (${listed}); EXCEPTION WHEN duplicate_object THEN NULL; END $$`;
}

const SCHEMA_STATEMENTS = [
  createEnumSql("OpenFlag", ["CLOSED", "OPEN"]),
  createEnumSql("TeamLeadership", ["MANAGER", "CAPTAIN"]),
  createEnumSql("TeamSeatKind", ["PRIMARY", "CO_MANAGER"]),
  createEnumSql("TeamFormat", ["STANDARD_5V5", "CUSTOM"]),
  createEnumSql("SpokenLanguage", [
    "FR",
    "EN",
    "DE",
    "ES",
    "IT",
    "PT",
    "PL",
    "RU",
    "KO",
    "JA",
    "ZH",
    "NL",
    "SV",
    "TR",
    "AR",
  ]),
  createEnumSql("TeamGrantRole", ["COACH", "ASSISTANT_COACH", "CAPTAIN"]),
  createEnumSql("InvitationKind", ["PLAYER", "COACH"]),
  createEnumSql("OfficialScrimSlot", [
    "NONE",
    "SCRIM_20H",
    "SCRIM_21H",
    "VOD_REVIEW",
    "TOURNOI",
    "CUSTOM",
    "TBD",
  ]),
  createEnumSql("ScrimMapPool", [
    "OFFICIEL",
    "ALTERNATIVE",
    "LOOSERPICK",
    "CUSTOM",
  ]),
  createEnumSql("ScrimLobbyHostPref", [
    "NOUS_UNIQUEMENT",
    "PREFERENCE_NOUS",
    "PEU_IMPORTE",
    "PREFERENCE_VOUS",
    "VOUS_UNIQUEMENT",
  ]),
  createEnumSql("ScrimProposalStatus", [
    "PENDING",
    "ACCEPTED",
    "REJECTED",
    "CANCELLED",
  ]),
  createEnumSql("ScrimCancellationReason", [
    "ROSTER_UNAVAILABLE",
    "TECHNICAL_ISSUE",
    "SCHEDULE_ERROR",
    "OTHER",
  ]),
  createEnumSql("AnnouncementType", ["SCRIM", "PLAYER", "TEAM", "SUB", "LFP"]),
  createEnumSql("AnnouncementStatus", ["ACTIVE", "EXPIRED"]),
  createEnumSql("AnnouncementPostStatus", [
    "PENDING",
    "SENDING",
    "SENT",
    "FAILED",
    "DELETED",
  ]),
  `ALTER TYPE "OfficialScrimSlot" ADD VALUE IF NOT EXISTS 'VOD_REVIEW'`,
  `ALTER TYPE "OfficialScrimSlot" ADD VALUE IF NOT EXISTS 'TOURNOI'`,
  `ALTER TYPE "OfficialScrimSlot" ADD VALUE IF NOT EXISTS 'CUSTOM'`,
  `ALTER TYPE "ScrimProposalStatus" ADD VALUE IF NOT EXISTS 'CANCELLED'`,
  `ALTER TYPE "AnnouncementType" ADD VALUE IF NOT EXISTS 'LFP'`,
  `ALTER TYPE "AnnouncementPostStatus" ADD VALUE IF NOT EXISTS 'SENDING'`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "pendingEmail" TEXT`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "discord" TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "isDiscordPublic" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "deactivatedAt" TIMESTAMP(3)`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "anonymizeAfter" TIMESTAMP(3)`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "anonymizedAt" TIMESTAMP(3)`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "discordId" TEXT`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "discordUsername" TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "discordDmBlocked" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "notifyDiscordMessages" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "notifyDiscordInvitations" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "notifyDiscordScrims" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "notifyDiscordCancellations" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "openToCast" "OpenFlag" NOT NULL DEFAULT 'CLOSED'`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "openToCoach" "OpenFlag" NOT NULL DEFAULT 'CLOSED'`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "user_discordId_key" ON "user"("discordId")`,
  `ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "language" "SpokenLanguage" NOT NULL DEFAULT 'FR'`,
  `ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "estimatedSr" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "leadership" "TeamLeadership" NOT NULL DEFAULT 'MANAGER'`,
  `ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "format" "TeamFormat" NOT NULL DEFAULT 'STANDARD_5V5'`,
  `ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "orgId" TEXT`,
  `ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "parentTeamId" TEXT`,
  `CREATE TABLE IF NOT EXISTS "TeamSeat" (
    "id" TEXT NOT NULL,
    "teamId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "kind" "TeamSeatKind" NOT NULL DEFAULT 'PRIMARY',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TeamSeat_pkey" PRIMARY KEY ("id")
  )`,
  `CREATE TABLE IF NOT EXISTS "TeamCoach" (
    "id" TEXT NOT NULL,
    "teamId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TeamCoach_pkey" PRIMARY KEY ("id")
  )`,
  `CREATE TABLE IF NOT EXISTS "TeamPermission" (
    "id" TEXT NOT NULL,
    "teamId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "role" "TeamGrantRole" NOT NULL,
    "canEditOfficialSchedule" BOOLEAN NOT NULL DEFAULT false,
    "canRecordScrim" BOOLEAN NOT NULL DEFAULT false,
    "canProposeScrim" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "TeamPermission_pkey" PRIMARY KEY ("id")
  )`,
  `CREATE TABLE IF NOT EXISTS "OpenPosition" (
    "id" TEXT NOT NULL,
    "teamId" TEXT NOT NULL,
    "role" "PlayerRole" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "OpenPosition_pkey" PRIMARY KEY ("id")
  )`,
  `CREATE TABLE IF NOT EXISTS "OpenPositionApplication" (
    "id" TEXT NOT NULL,
    "positionId" TEXT NOT NULL,
    "playerId" TEXT NOT NULL,
    "conversationId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "OpenPositionApplication_pkey" PRIMARY KEY ("id")
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "TeamSeat_teamId_userId_key" ON "TeamSeat"("teamId", "userId")`,
  `CREATE INDEX IF NOT EXISTS "TeamSeat_userId_idx" ON "TeamSeat"("userId")`,
  `CREATE INDEX IF NOT EXISTS "TeamSeat_teamId_kind_idx" ON "TeamSeat"("teamId", "kind")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "TeamCoach_teamId_userId_key" ON "TeamCoach"("teamId", "userId")`,
  `CREATE INDEX IF NOT EXISTS "TeamCoach_userId_idx" ON "TeamCoach"("userId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "TeamPermission_teamId_userId_key" ON "TeamPermission"("teamId", "userId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "OpenPosition_teamId_role_key" ON "OpenPosition"("teamId", "role")`,
  `DO $$ BEGIN ALTER TABLE "TeamSeat" ADD CONSTRAINT "TeamSeat_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN ALTER TABLE "TeamSeat" ADD CONSTRAINT "TeamSeat_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN ALTER TABLE "TeamCoach" ADD CONSTRAINT "TeamCoach_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN ALTER TABLE "TeamCoach" ADD CONSTRAINT "TeamCoach_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN ALTER TABLE "TeamPermission" ADD CONSTRAINT "TeamPermission_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN ALTER TABLE "OpenPosition" ADD CONSTRAINT "OpenPosition_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `CREATE TABLE IF NOT EXISTS "TeamScrimConfig" (
    "id" TEXT NOT NULL,
    "teamId" TEXT NOT NULL,
    "discordManager" TEXT NOT NULL DEFAULT '',
    "battleTagContact" TEXT NOT NULL DEFAULT '',
    "stagger" BOOLEAN NOT NULL DEFAULT false,
    "povStream" BOOLEAN NOT NULL DEFAULT false,
    "mapPool" "ScrimMapPool" NOT NULL DEFAULT 'OFFICIEL',
    "lobbyHost" "ScrimLobbyHostPref" NOT NULL DEFAULT 'PEU_IMPORTE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "TeamScrimConfig_pkey" PRIMARY KEY ("id")
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "TeamScrimConfig_teamId_key" ON "TeamScrimConfig"("teamId")`,
  `DO $$ BEGIN ALTER TABLE "TeamScrimConfig" ADD CONSTRAINT "TeamScrimConfig_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `CREATE TABLE IF NOT EXISTS "OfficialSchedule" (
    "id" TEXT NOT NULL,
    "teamId" TEXT NOT NULL,
    "weekStartDate" DATE NOT NULL,
    "monday" "OfficialScrimSlot" NOT NULL DEFAULT 'NONE',
    "tuesday" "OfficialScrimSlot" NOT NULL DEFAULT 'NONE',
    "wednesday" "OfficialScrimSlot" NOT NULL DEFAULT 'NONE',
    "thursday" "OfficialScrimSlot" NOT NULL DEFAULT 'NONE',
    "friday" "OfficialScrimSlot" NOT NULL DEFAULT 'NONE',
    "saturday" "OfficialScrimSlot" NOT NULL DEFAULT 'NONE',
    "sunday" "OfficialScrimSlot" NOT NULL DEFAULT 'NONE',
    "mondayNote" TEXT NOT NULL DEFAULT '',
    "tuesdayNote" TEXT NOT NULL DEFAULT '',
    "wednesdayNote" TEXT NOT NULL DEFAULT '',
    "thursdayNote" TEXT NOT NULL DEFAULT '',
    "fridayNote" TEXT NOT NULL DEFAULT '',
    "saturdayNote" TEXT NOT NULL DEFAULT '',
    "sundayNote" TEXT NOT NULL DEFAULT '',
    "matchSlots" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "OfficialSchedule_pkey" PRIMARY KEY ("id")
  )`,
  `ALTER TABLE "OfficialSchedule" ADD COLUMN IF NOT EXISTS "mondayNote" TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE "OfficialSchedule" ADD COLUMN IF NOT EXISTS "tuesdayNote" TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE "OfficialSchedule" ADD COLUMN IF NOT EXISTS "wednesdayNote" TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE "OfficialSchedule" ADD COLUMN IF NOT EXISTS "thursdayNote" TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE "OfficialSchedule" ADD COLUMN IF NOT EXISTS "fridayNote" TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE "OfficialSchedule" ADD COLUMN IF NOT EXISTS "saturdayNote" TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE "OfficialSchedule" ADD COLUMN IF NOT EXISTS "sundayNote" TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE "OfficialSchedule" ADD COLUMN IF NOT EXISTS "matchSlots" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[]`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "OfficialSchedule_teamId_weekStartDate_key" ON "OfficialSchedule"("teamId", "weekStartDate")`,
  `CREATE INDEX IF NOT EXISTS "OfficialSchedule_matchSlots_idx" ON "OfficialSchedule" USING GIN ("matchSlots")`,
  `DO $$ BEGIN ALTER TABLE "OfficialSchedule" ADD CONSTRAINT "OfficialSchedule_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `CREATE TABLE IF NOT EXISTS "ScrimProposal" (
    "id" TEXT NOT NULL,
    "fromTeamId" TEXT NOT NULL,
    "toTeamId" TEXT NOT NULL,
    "weekStartDate" DATE NOT NULL,
    "weekday" TEXT NOT NULL,
    "slot" "OfficialScrimSlot" NOT NULL,
    "status" "ScrimProposalStatus" NOT NULL DEFAULT 'PENDING',
    "createdById" TEXT NOT NULL,
    "cancellationReason" "ScrimCancellationReason",
    "cancellationDetails" TEXT NOT NULL DEFAULT '',
    "cancelledAt" TIMESTAMP(3),
    "cancelledById" TEXT,
    "cancelledByTeamId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "respondedAt" TIMESTAMP(3),
    CONSTRAINT "ScrimProposal_pkey" PRIMARY KEY ("id")
  )`,
  `ALTER TABLE "ScrimProposal" ADD COLUMN IF NOT EXISTS "cancellationReason" "ScrimCancellationReason"`,
  `ALTER TABLE "ScrimProposal" ADD COLUMN IF NOT EXISTS "cancellationDetails" TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE "ScrimProposal" ADD COLUMN IF NOT EXISTS "cancelledAt" TIMESTAMP(3)`,
  `ALTER TABLE "ScrimProposal" ADD COLUMN IF NOT EXISTS "cancelledById" TEXT`,
  `ALTER TABLE "ScrimProposal" ADD COLUMN IF NOT EXISTS "cancelledByTeamId" TEXT`,
  `CREATE INDEX IF NOT EXISTS "ScrimProposal_toTeamId_status_idx" ON "ScrimProposal"("toTeamId", "status")`,
  `CREATE INDEX IF NOT EXISTS "ScrimProposal_fromTeamId_status_idx" ON "ScrimProposal"("fromTeamId", "status")`,
  `DO $$ BEGIN ALTER TABLE "ScrimProposal" ADD CONSTRAINT "ScrimProposal_fromTeamId_fkey" FOREIGN KEY ("fromTeamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN ALTER TABLE "ScrimProposal" ADD CONSTRAINT "ScrimProposal_toTeamId_fkey" FOREIGN KEY ("toTeamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN ALTER TABLE "ScrimProposal" ADD CONSTRAINT "ScrimProposal_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `CREATE TABLE IF NOT EXISTS "Announcement" (
    "id" TEXT NOT NULL,
    "teamId" TEXT NOT NULL,
    "structureId" TEXT,
    "createdById" TEXT NOT NULL,
    "type" "AnnouncementType" NOT NULL,
    "content" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "discordMessageId" TEXT NOT NULL DEFAULT '',
    "discordMessageIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "channelId" TEXT NOT NULL DEFAULT '',
    "status" "AnnouncementStatus" NOT NULL DEFAULT 'ACTIVE',
    "snapshot" JSONB,
    "openPositionId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Announcement_pkey" PRIMARY KEY ("id")
  )`,
  `ALTER TABLE "Announcement" ADD COLUMN IF NOT EXISTS "discordMessageIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[]`,
  `ALTER TABLE "Announcement" ADD COLUMN IF NOT EXISTS "openPositionId" TEXT`,
  `CREATE TABLE IF NOT EXISTS "AnnouncementPost" (
    "id" TEXT NOT NULL,
    "announcementId" TEXT NOT NULL,
    "channelId" TEXT NOT NULL,
    "guildId" TEXT NOT NULL DEFAULT '',
    "discordMessageId" TEXT NOT NULL DEFAULT '',
    "status" "AnnouncementPostStatus" NOT NULL DEFAULT 'PENDING',
    "lastError" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "AnnouncementPost_pkey" PRIMARY KEY ("id")
  )`,
  `ALTER TABLE "AnnouncementPost" ADD COLUMN IF NOT EXISTS "guildId" TEXT NOT NULL DEFAULT ''`,
  `CREATE INDEX IF NOT EXISTS "Announcement_status_expiresAt_idx" ON "Announcement"("status", "expiresAt")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "AnnouncementPost_announcementId_channelId_key" ON "AnnouncementPost"("announcementId", "channelId")`,
  `DO $$ BEGIN ALTER TABLE "Announcement" ADD CONSTRAINT "Announcement_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN ALTER TABLE "Announcement" ADD CONSTRAINT "Announcement_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN ALTER TABLE "AnnouncementPost" ADD CONSTRAINT "AnnouncementPost_announcementId_fkey" FOREIGN KEY ("announcementId") REFERENCES "Announcement"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `CREATE TABLE IF NOT EXISTS "DiscordServerConfig" (
    "guildId" TEXT NOT NULL,
    "scrimChannelId" TEXT NOT NULL DEFAULT '',
    "playerChannelId" TEXT NOT NULL DEFAULT '',
    "teamChannelId" TEXT NOT NULL DEFAULT '',
    "ringerChannelId" TEXT NOT NULL DEFAULT '',
    "guildName" TEXT NOT NULL DEFAULT '',
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DiscordServerConfig_pkey" PRIMARY KEY ("guildId")
  )`,
  `ALTER TABLE "DiscordServerConfig" ADD COLUMN IF NOT EXISTS "playerChannelId" TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE "DiscordServerConfig" ADD COLUMN IF NOT EXISTS "teamChannelId" TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE "DiscordServerConfig" ADD COLUMN IF NOT EXISTS "ringerChannelId" TEXT NOT NULL DEFAULT ''`,
];

let ensurePromise: Promise<void> | null = null;

export async function ensureAppSchema(db: PrismaClient): Promise<void> {
  if (!ensurePromise) {
    ensurePromise = (async () => {
      for (const statement of SCHEMA_STATEMENTS) {
        try {
          await db.$executeRawUnsafe(statement);
        } catch (error) {
          console.error(
            "[db] schema ensure statement failed",
            statement.slice(0, 88),
            error,
          );
        }
      }
    })().catch((error) => {
      ensurePromise = null;
      console.error("[db] schema ensure", error);
    });
  }
  await ensurePromise;
}
